### ISSUE TITLE
enter button on NumericInput

### ISSUE THREAD

**Issue by kenkotch** [viclm/numeric-keyboard#10]
Hi, 
How do I change the NumericInput label on the enter button and set a custom function on `Enter` press?
Thank you

**Comment by viclm** [comment]
1.  Prop `entertext ` is used for custom label of enter button. To custom the keyboard works in NumericInput, checkout the `keyboard` prop.
2. It's impossible to capture the keyboard event in NumericInput right now. I will work out a solution later,

**Comment by viclm** [comment]
Prop `entertext` is used for changing the label of enter button.
Event `enterpress` is triggered when enter button is pressed
