### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by chen-can** [viclm/numeric-keyboard#12]
用上amfe-flexible 不能够适配

**Comment by chen-can** [comment]
还有在iphone safari 浏览器中 底部会被遮挡

**Comment by chen-can** [comment]
在iphone 中在数字中间插入数值输入完一个后会立刻跳到最后一位数 作者有空解决下 谢谢啦

**Comment by viclm** [comment]
> 还有在iphone safari 浏览器中 底部会被遮挡

可以提供下手机、系统版本和页面结构吗，是键盘被遮挡还是什么，多谢？

**Comment by viclm** [comment]
> 用上amfe-flexible 不能够适配

是这个吗 https://github.com/amfe/lib-flexible，已经被弃用了呢，可否使用替代方案呢？

**Comment by chen-can** [comment]
iphone7\ios10\键盘挡住Safari 底部导航

**Comment by lijundong** [comment]
> iphone7\ios10\键盘挡住Safari 底部导航

您好，方便提供页面截图吗，我这里  iOS 10.3.2 的 7P 未复现问题

**Comment by viclm** [comment]
> 在iphone 中在数字中间插入数值输入完一个后会立刻跳到最后一位数 作者有空解决下 谢谢啦

fixed in https://github.com/viclm/numeric-keyboard/commit/ef9ae31a7e7db77ef859112f4fd98713e192c1c6
