### ISSUE TITLE
usage for pin

### ISSUE THREAD

**Issue by tekkenking** [viclm/numeric-keyboard#15]
Lovely work you gave to the community..
Though i haven't installed the keyboard, and the reason was because i am not sure if this can be used as a pin entry.

I am currently developing an ionic 4 app, and i was hoping i could use this numeric keyboard to achieve pin entry such that, number pad is displayed and the characters would be in password type.

I would like to confirm if this is possible this piece.

Thanks in adv.

**Comment by viclm** [comment]
Sorry cannot catch your point. Do you mean the effect of password panel?  I update the snapshot to gif in README. Check the demo code if it is the right effect.

**Comment by tekkenking** [comment]
Yeah, the gif reflects my questions.
How would i achieve the pin effect?

**Comment by viclm** [comment]
> Yeah, the gif reflects my questions.
> How would i achieve the pin effect?

Code for gif is in demo directory
