### ISSUE TITLE
引入组件报错

### ISSUE THREAD

**Issue by zheng10005** [viclm/numeric-keyboard#16]
![image](https://user-images.githubusercontent.com/29821139/56075832-7efa0600-5dfb-11e9-99e0-039c49205d93.png)

**Comment by viclm** [comment]
@zheng10005 可以留下错误原因和解决方案呢？

**Comment by zheng10005** [comment]
看到其他issue了 是vue3 导致的，根据你在那个问题回复的方法解决了

**Comment by viclm** [comment]
Duplicate of #9
