### ISSUE TITLE
when prop 'format' is function,the last character can not be deleted

### ISSUE THREAD

**Issue by zheng10005** [viclm/numeric-keyboard#17]
![image](https://user-images.githubusercontent.com/29821139/56077286-f7b58e00-5e0c-11e9-97d8-df228520ae44.png)
![image](https://user-images.githubusercontent.com/29821139/56077288-000dc900-5e0d-11e9-997a-7a1e45541ad4.png)

------------------------------------------------------
here is my way to solve this:

...
`if(newValue===''){
          _this2.set('value', newValue);

          _this2.set('rawValue', newRawValue);

          _this2.set('cursorPos', isAdd ? cursorPos + 1 : cursorPos - 1);

          _this2.dispatch('input', newValue);
      }else if (formatFn(newValue)) {
        if (type === 'number') {
          if (!RNumber.test(newValue)) {
            return;
          }

          newValue = parseFloat(newValue, 10);

          if (isNaN(newValue)) {
            newValue = '';
          }
        } else if (newValue.length > maxlength || type === 'tel' && !RTel.test(newValue)) {
          return;
        }

        _this2.set('value', newValue);

        _this2.set('rawValue', newRawValue);

        _this2.set('cursorPos', isAdd ? cursorPos + 1 : cursorPos - 1);

        _this2.dispatch('input', newValue);
      }`
...

I add a jugement when newValue equals '',if there is other way ,please point out

**Comment by viclm** [comment]
The `format` function should return a boolean value
