### ISSUE TITLE
运行在浏览器 TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by XinLi96** [viclm/numeric-keyboard#18]

**Comment by viclm** [comment]
#16

**Comment by zebpaypeswani** [comment]
Hi I am facing same issue. Any update on this?

**Comment by viclm** [comment]
> Hi I am facing same issue. Any update on this?

Is the solution in #9 not ok?

**Comment by zebpaypeswani** [comment]
thanks for the quick reply this works. How can I change the number layout in keyboard. for e.g
I want keyboard to be like 
7 8 9
4 5 6
1 2 3
--------
confirm

**Comment by viclm** [comment]
> thanks for the quick reply this works. How can I change the number layout in keyboard. for e.g
> I want keyboard to be like
> **7 8 9 4 5 6 1 2 3**

The `layout` property is ready for you. Check out the demo code.
