### ISSUE TITLE
在vue项目中资源引入报错，为什么的？我感到很困惑

### ISSUE THREAD

**Issue by WangZhenHao** [viclm/numeric-keyboard#29]
没有配置webpack的resolve， 直接引入的时候为什么会报错的呢
![2](https://user-images.githubusercontent.com/26181934/67930578-045bd100-fbfb-11e9-84ad-4aff62027032.jpg)

![image](https://user-images.githubusercontent.com/26181934/67932732-67e7fd80-fbff-11e9-87c4-d75ee4eefafe.png)

**Comment by WangZhenHao** [comment]
是vue-cli3的配置问题

**Comment by viclm** [comment]
> 是vue-cli3的配置问题

解决了？

**Comment by WangZhenHao** [comment]
> > 是vue-cli3的配置问题
> 
> 解决了？
参考你之前在issue说明的vue-cli3里面的配置就可以，如果我没有配置webpack中的resolve.alias，而是直接引入，就会报错！

**Comment by viclm** [comment]
> > > 是vue-cli3的配置问题
> > 
> > 
> > 解决了？
> > 参考你之前在issue说明的vue-cli3里面的配置就可以，如果我没有配置webpack中的resolve.alias，而是直接引入，就会报错！

ok，那我关了

**Comment by WangZhenHao** [comment]
> > > > 是vue-cli3的配置问题
> > > 
> > > 
> > > 解决了？
> > > 参考你之前在issue说明的vue-cli3里面的配置就可以，如果我没有配置webpack中的resolve.alias，而是直接引入，就会报错！
> 
> ok，那我关了

import { NumericKeyboard, NumericInput, Keys } from 'numeric-keyboard/numeric_keyboard.vue.js'
我的疑惑是为什么直接移入会报错的呢？？？我想不太明白，可以解惑一下吗（你在#9的issue里面用英文说了一下，但是我看不太懂说明意思），谢谢！

**Comment by viclm** [comment]
> > > > > 是vue-cli3的配置问题
> > > > 
> > > > 
> > > > 解决了？
> > > > 参考你之前在issue说明的vue-cli3里面的配置就可以，如果我没有配置webpack中的resolve.alias，而是直接引入，就会报错！
> > 
> > 
> > ok，那我关了
> 
> import { NumericKeyboard, NumericInput, Keys } from 'numeric-keyboard/numeric_keyboard.vue.js'
> 我的疑惑是为什么直接移入会报错的呢？？？我想不太明白，可以解惑一下吗（你在#9的issue里面用英文说了一下，但是我看不太懂说明意思），谢谢！

意思就是 numeric-keyboard 提供的包是不需要 webpack loader 处理的，如果处理可能产生意外错误。一般来讲，webpack loader 也都是将 node_modules 排除在外

**Comment by WangZhenHao** [comment]
明白，谢谢
