### ISSUE TITLE
引入numeric-keyboard插件的时候不去配置webpack中的reslove.alias为什么不行呢？

### ISSUE THREAD

**Issue by WangZhenHao** [viclm/numeric-keyboard#30]
是否抱歉再次提出issue!

import { NumericKeyboard, NumericInput, Keys } from 'numeric-keyboard/dist/numeric_keyboard.vue.js'
我的疑惑是为什么直接移入会报错的呢？？？我想不太明白，可以解惑一下吗（你在#9的issue里面用英文说了一下，但是我看不太懂说明意思），十分感谢！

**Comment by viclm** [comment]
因为 numeric-keyboard 支持 vue react ng vanilla 四种版本，我没法设置一个默认的，所以推荐业务方自己设置 alias 对应自己的技术栈。

**Comment by WangZhenHao** [comment]
哦哦，谢谢
