### ISSUE TITLE
NumericKeyboard is not working 

### ISSUE THREAD

**Issue by duanhuiwen** [viclm/numeric-keyboard#8]
the following piece prompt ` Cannot read property 'init' of undefined`

```
import { NumericKeyboard } from 'numeric-keyboard'
class App extends React.Component {
  press(key) {
    ...
  }
  render() {
    return <div className="keyboard">
      <NumericKeyboard layout="tel" onPress={this.press.bind(this)} />
    </div>
  }
}
```

**Comment by viclm** [comment]
Sorry! The code in README shows the basic usage of the component which may be not working in real environment. I will fix that later, before that you can pay around with the "real" code in demo/react directory, thanks!

**Comment by viclm** [comment]
Try playing around with demo/. Let me know if it doesn't work!
